"""changed date id

Revision ID: 41484c242bf6
Revises: 909d2894265f
Create Date: 2023-06-17 14:31:25.327379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41484c242bf6'
down_revision = '909d2894265f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reservation_date', sa.Date(), nullable=False))
        batch_op.drop_constraint('uq_reservations_location_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_reservations_location_id'), ['location_id', 'customer_id', 'reservation_date'])
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_reservations_location_id'), type_='unique')
        batch_op.create_unique_constraint('uq_reservations_location_id', ['location_id', 'customer_id', 'date'])
        batch_op.drop_column('reservation_date')

    # ### end Alembic commands ###
